kind: pipeline
name: arm
platform: { os: linux, arch: arm }
steps:
- name: Test
  image: buildpack-deps:impish
  commands:
    - export LC_ALL=C.UTF-8
    - apt-get update -y
    - apt-get install -y ghc cabal-install
    - cabal --version
    - cabal update
    - cabal new-test
