name: ci
on:
  push:
    branches:
      - master
      - bytestring-0.11
      - sse-count
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        ghc: ['latest']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Update cabal package database
      run: cabal update
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
          tests/dist-newstyle
          bench/dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Build
      run: |
        cabal sdist -z -o .
        cabal get bytestring-*.tar.gz
        cd bytestring-*/
        cabal build all
    - name: Test
      working-directory: ./tests
      run: cabal test --test-show-details=direct
    - name: Bench
      working-directory: ./bench
      run: cabal bench --benchmark-options=-l
    - name: Haddock
      run: cabal haddock
