name: ci
on:
  push:
    branches:
      - master
      - bytestring-0.11
  pull_request: {} # Validate all PRs

defaults:
  run:
    shell: bash

jobs:
  arm:
    # needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
        - os: [self-hosted, Linux, ARM64, aarch32-linux]
        - os: [self-hosted, macOS, aarch64]
    steps:
    - name: Install
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 sh
    - uses: actions/checkout@v1
    - name: Test
      run: |
        source ~/.ghcup/env
        cabal update
        cabal test
